name: CI/CD
on: [push, pull_request]

jobs:
  golangci-lint:
    name: linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: ./
        with:
          args: --config=./golangci.yaml ./...

  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: make build
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
