name: CI/CD
on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57
          args: --config=.golangci.yml ./...

  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: make build
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
